version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "madina-17"
      POSTGRES_DB: "notes"
    volumes:
      - dbdata:/data/db
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: Notes/Dockerfile
      #depends_on: postgres
volumes:
  dbdata: 